FROM apache/superset:latest

USER root

RUN apt-get update && \
    apt-get install -y gcc libpq-dev && \
    rm -rf /var/lib/apt/lists/*

RUN /app/.venv/bin/pip install --no-cache-dir psycopg2-binary

USER superset